baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Piero's Portfolio"
theme = "basic"
[params]
  author = "Piero Cascio"
  description = "My portfolio site"
  googleAnalytics = "UA-xxxxxxxxxxxx"
  gh_url = "https://api.github.com/users"
  gh_user = "pietrocascio"
